# SPDX-FileCopyrightText: 2021 Open Networking Foundation <info@opennetworking.org>
#
# SPDX-License-Identifier: Apache-2.0
# SPDX-License-Identifier: LicenseRef-ONF-Member-Only-1.0

---
info:
  version: 1.0.0
  description: GNBSIM initial local configuration
configuration:
  gnbs: # pool of gNodeBs
    gnb1:
      ipAddr: # gNB IP address used to connect to AMF 
      port: 9487 # gNB Port used to connect to AMF
      name: gnb1 # gNB name that uniquely identify a gNB within application
      gnbId: 000102 # gNB identifier (3 bytes hex string, range: 000000~FFFFFF)
      tac: 000001 # Tracking Area Code (3 bytes hex string, range: 000000~FFFFFF)
      defaultAmf:
        hostName: amf # Host name of AMF
        ipAddr: # AMF IP address
        port: 38412 # AMF port
  profiles: # profile information
    - profileType: register # profile type
      profileName: profile1 # uniqely identifies a profile within application
      enable: true # Set true to execute the profile, false otherwise.
      gnbName: gnb1 # gNB to be used for this profile
      startImsi: imsi-2089300007487
      ueCount: 1
      plmnId: # Public Land Mobile Network ID, <PLMN ID> = <MCC><MNC>
        mcc: 208 # Mobile Country Code (3 digits string, digit: 0~9)
        mnc: 93 # Mobile Network Code (2 or 3 digits string, digit: 0~9)